"""Auto-generated pytest module from test/test_schematics_working_kinds.py

This file was generated by pytest_iproxy_adapter to convert IProxy
test objects into regular pytest functions.
"""

# Import the conversion utilities
from test.pytest_iproxy_adapter import convert_module_iproxy_tests

# Convert all IProxy tests from the source module
_pytest_tests = convert_module_iproxy_tests("test/test_schematics_working_kinds.py")

# Create module-level test functions

test_working = _pytest_tests['test_working']