name: Mirror to Proboscis

on:
  push:
    branches: [ main ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:proboscis/ml-nexus.git
          ssh_private_key:
            ${{ secrets.MIRROR_SSH_PRIVATE_KEY }}
